In [ ]:
#H Hacemos los imports correspondientes a numpy
import numpy as np
import numpy.linalg as lng

### Ejemplos
Algunos ejemplos de operaciones matriciales básicas disponibles en numpy

In [ ]:
# Distintas maneras de inicializar una matriz
A = np.array([[1,2],[3,4]])
B = np.array(np.mat('9 10; 11 12')) # Subclase
C = np.array([[5,6],[7,8]], dtype=float)

# Para los vectores usamos matrices por columnas
v = np.array([[11],[12]])
w = np.array(np.mat('17; 18')) # Subclase
x = np.array([21,22,23,24], ndmin=4)

In [ ]:
#A + np.arange(2)

In [ ]:
# Matrices especiales
I = np.eye(3) # Identidad de 3x3
D = np.diag([77,90]) # Matriz diagonal
N = np.zeros((3,4)) # Matriz nula de 3x3

# Operaciones basicas entre matrices y vectores
A + B       # Suma
A - B       # Resta
A @ B       # Producto de matrices
A @ v       # Producto de matriz por vector
3.2 * A     # Producto por escalar
A**2        # Potencia
A.T         # Traspuesta (transpose())
lng.inv(A)  # Inversa

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

### Ejercicio 1
Dados x<sub>1</sub>, ..., x<sub>n</sub> una muestra de una variable aleatoria, implementar rutinas que calculen la media y la varianza utilizando operaciones vectoriales.

In [ ]:
x = np.arange(10)

def mean(x):
    sum = 0
    for i in x:
      sum = sum + i
    return sum / x.size

print(mean(x))
    
def var(x):
    prom = mean(x)
    sum = 0
    for i in x:
      sum += (i - prom) ** 2
    return sum / x.size

print(var(x))
    

4.5
8.25


In [ ]:
N = 4
x = np.array(np.random.rand(N,1))
print("x:" + str(x) + "\n media: " + str(mean(x)) + " varianza: " + str(var(x)))
assert(np.abs(mean(x) - np.mean(x)) < 1e-6 )
assert(np.abs(var(x) - np.var(x)) < 1e-6 )
print("OK")

x:[[0.98559004]
 [0.83300459]
 [0.56160253]
 [0.9174814 ]]
 media: [0.82441964] varianza: [0.02594573]
OK


### Ejercicio 2
Sea A matriz en R<sup>m×n</sup><br>
1. Demostrar que A<sup>t</sup> A y AA<sup>t</sup> son simétricas<br>
2. Implementar una rutina que dada una matriz cuadrada verifique si la misma es simétrica

In [ ]:
def esSimetrica(A): 
  print(A)
  return np.allclose(A,A.T)
    # COMPLETAR
    


In [ ]:
A = np.array([[1,2],[2,6],[3,7],[4,8]])
B = np.random.rand(4,4)

print("A: \n"  + str(A))
print("B: \n" + str(B))
assert(esSimetrica(A @ A.T))
assert(esSimetrica(B.T @ B))
print("OK")

A: 
[[1 2]
 [2 6]
 [3 7]
 [4 8]]
B: 
[[0.94324641 0.81747033 0.08165522 0.96709442]
 [0.9967538  0.1478719  0.11449438 0.2402945 ]
 [0.50288866 0.99883298 0.75770149 0.09406764]
 [0.94842667 0.85939974 0.12293622 0.99375075]]
[[ 5 14 17 20]
 [14 40 48 56]
 [17 48 58 68]
 [20 56 68 80]]


TypeError: ignored

### Ejercicio 3

Analizar la función implementada en el item anterior con la matriz B generada de la siguiente forma:

`A = np.random.rand(4,4)
B = A.T * A * 0.1 / 0.1`

Analizar el resultado, revisar la implementación y (eventualmente) reimplementar la función.

In [ ]:
D = np.array(np.diag([1,2]))
I = np.array(np.eye(5))
A = np.random.rand(4,4)

print(A)
assert(not(esSimetrica(A)))

# Ojo! usamos @ para el producto matricial
assert(esSimetrica(A.T@(A*0.10)/0.10))
assert(esSimetrica(D) and esSimetrica(I))
print("Ok")

[[0.92567991 0.2548934  0.28494302 0.43387066]
 [0.51318896 0.02852458 0.23373903 0.19954862]
 [0.40011516 0.20812569 0.0151232  0.89934521]
 [0.70024236 0.87620829 0.19681646 0.27508787]]
[[0.92567991 0.2548934  0.28494302 0.43387066]
 [0.51318896 0.02852458 0.23373903 0.19954862]
 [0.40011516 0.20812569 0.0151232  0.89934521]
 [0.70024236 0.87620829 0.19681646 0.27508787]]
[[1.77067771 0.9474206  0.52758856 1.05650133]
 [0.9474206  0.87684156 0.25489714 0.54449392]
 [0.52758856 0.25489714 0.17479189 0.23801351]
 [1.05650133 0.54449392 0.23801351 1.11255854]]
[[1 0]
 [0 2]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Ok


### Ejercicio 4
Sean A, B en R<sup>n×n</sup>, con n par y B triangular inferior,
1. Realizar la multiplicación AB por bloques, partiendo ambas matrices en bloques de tamaño n/2.
2. Implementar una rutina que realice la multiplicación por bloques, **evitando cuentas innecesarias**.

In [ ]:
import math

def block_multiplication(A,B): 
    
    n = A.shape[0]
    assert(n % 2 == 0)
    mid = math.floor(n/2)
    
    # Completar
    A11 = A[:mid,:mid]
    A12 = A[:mid,mid:]
    A21 = A[mid:,:mid]
    A22 = A[mid:,mid:]
    
    B11 = B[:mid,:mid]
    B12 = B[:mid,mid:]
    B21 = B[mid:,:mid]
    B22 = B[mid:,mid:]

    C_11 = A11 @ B11 + A12 @ B21
    C_12 = A11 @ B12 + A12 @ B22
    C_21 = A21 @ B11 + A22 @ B21
    C_22 = A21 @ B12 + A22 @ B22

    return np.block([[C_11,C_12],[C_21,C_22]])


In [ ]:
N = 4
A = np.array(np.random.rand(N,N))
B = np.array(np.random.rand(N,N))
assert(np.allclose(A @ B,block_multiplication(A,B)))

print("Ok")

Ok


### Ejercicio 5
Describir e implementar un algoritmo que calcule un vector no nulo $z \in  \mathbb{R}^{n}$ tal que $Uz = 0$, donde $U \in  \mathbb{R}^{nxn}$ sea una matriz triangular superior con $u_{nn} = 0$ y $u_{ii} \neq 0 \ i \neq n$