# Numpy (Baby steps)

In [ ]:
import numpy as np

## Arrays

Los arrays son el tipo de datos más importante que provee NumPy. En su versión más básica representan vectores pero pueden tener más dimensiones y representar matrices y tensores en general.

El tipo se llama ndarray pero también se lo conoce en la librería simplemente como array.

En su versión más simple podemos pensar que no es más que una lista de python pero:
 
* A diferencia de las listas en python, solo pueden tener un tipo de datos adentro.
* Existen un montón de operaciones matemáticas definidas y optimizadas para trabajar con este tipo de datos.

Al ser una clase de python, además de métodos tiene atributos. Veamos algunos de ellos 

In [ ]:
an_array = np.arange(20)
an_array

In [ ]:
an_array.shape

In [ ]:
an_array.ndim

In [ ]:
an_array.size

In [ ]:
an_array.dtype

## Matrices

Las matrices no son más que array con 2 dimensiones. Si bien existe un tipo específico para matrices en numpy cayó en desuso (y obsolescencia).

In [ ]:
a_matrix = np.arange(16).reshape(4,4)
a_matrix

In [ ]:
print(a_matrix.shape, a_matrix.ndim, a_matrix.size, a_matrix.dtype)

## Reshape

Las dimensiones de un array se pueden manipular como se vió en el ejemplo de creación de la matriz.

Algunos métodos que modifican las dimensiones:
* reshape: Devuelve un nuevo array con las dimensiones indicadas cómo
parámetro. Si alguno de los parámetros es igual a -1, se calculan las
dimensiones para que sea factible el cambio.

* resize: el mismo efecto que “reshape” pero modifica el array en vez de devolver
uno nuevo.
* T: sirve para transponer una matriz.

* ravel: “aplana” el array devolviendo todo en una sola dimensión.

In [ ]:
a_matrix

**EJERCICIO**: Dar dos formas para crear una nueva matriz, a partir de a_matrix, cuya dimensión sea (8,2)

In [ ]:
another_matrix = None
print(another_matrix.shape, a_matrix.shape)

**EJERCICIO**: Dar dos formas para modificar el shape de a_matrix a (8,2)

In [ ]:
...
print(a_matrix.shape)

In [ ]:
a_matrix.T

In [ ]:
a_matrix.ravel()

## Armando arrays

Por un lado, tenemos el constructor de la clase que admite como parámetro listas de valores .Por otro lado, existen diversas funciones que crean arrays. Veamos algunas

In [ ]:
np.array([1,2,3,4])

In [ ]:
np.arange(10,30,2)

In [ ]:
np.linspace(0.1,0.5,4)

In [ ]:
np.logspace(1,10,10)

In [ ]:
np.zeros((3,2))

In [ ]:
np.ones((2,3))

In [ ]:
np.random.standard_normal((8,2))

## Operaciones sobre arrays

Existen muchísimas operaciones definidas para arrays.

### Operadores básicos:

Los operadores básicos de sumas, restas, potencias, etc se encuentran sobrecargados.

In [ ]:
v = np.arange(1,7)
w = np.ones(6)
v, w

In [ ]:
v + w

In [ ]:
v - w

In [ ]:
v ** 2

In [ ]:
np.sqrt(v)

In [ ]:
print(np.sin(v), "\n", np.cos(v), "\n", np.floor(np.cos(v)), "\n", np.round(np.cos(v)))

### Operaciones entre vectores

#### Producto iterno (o escalar)

In [ ]:
np.dot(v,w)

In [ ]:
np.outer(v,w)

In [ ]:
M1 = np.arange(1,10).reshape(3,3)
M2 = np.ones((3,3))
M1, M2

### Multiplicación de matrices

Existe la multiplicación clásica entre matrices (con
el símbolo @) o lo que es el producto punto de matrices.

In [ ]:
M1 * M2

In [ ]:
M1 @ M2
#np.matmul(m1,m2)

**EJERCICIO**: Multiplicar $M_{1}v$ siendo $v = (1,1,1)$ como columna

In [ ]:
...

### Otras operaciones 

**EJERCICIO**: Multiplicar $M_{1}$ por un escalar

In [ ]:
...

**EJERCICIO**: Sumar fila a fila el vector $(1,0,1) $ a $M_{1}$ 

In [ ]:
...

Dado un operador, si las matrices no tienen el mismo tamaño Numpy tiene reglas definidas para "estirar", en alguna dimensión conveniente, una de las matrices y así arreglarselas para computar la operación. Esto se lo conoce como **Broadcasting**. Más info https://numpy.org/doc/stable/user/basics.broadcasting.html

## Universal functions y Performance

Son todas aquellas funciones que operan elemento a elemento sobre un array de manera predefinida. 

Varios de los ejemplos vistos en las slides anteriores caen en este tipo de funciones.

Estas funciones se dicen que son vectorizadas y están particularmente
optimizadas para hacer muy rápidamente la misma función sobre todas las
posiciones de un vector de manera muy rápida (sí, numpy usa SIMD https://github.com/numpy/numpy/blob/main/numpy/core/src/umath/simd.inc.src)

Se podría perfectamente obtener el mismo resultado iterando el array y
aplicando la función requerida, pero tomaría mucho más tiempo de cómputo.

### Performance

In [ ]:
import time
import math

def compute_sin_native(array):
    result = []
    for element in array:
        result.append(math.sin(element))
    return result

def compute_sin_numpy(array):
    result = np.sin(array)
    return result


In [ ]:
an_array = np.arange(10000000)
start_time_native = time.time()
result_native = compute_sin_native(an_array)
end_time_native = time.time()

start_time_numpy = time.time()
result_numpy = compute_sin_numpy(an_array)
end_time_numpy = time.time()
print("Time without numpy:", end_time_native - start_time_native)
print("Time with numpy:", end_time_numpy - start_time_numpy)
assert(np.allclose(result_native, result_numpy))

## Acceso e iteración

Los arrays en NumPy se pueden acceder a posiciones particulares o mediante slicing de maneras parecidas a las listas nativas.

In [ ]:
an_array = np.arange(0,40,2)
an_array

In [ ]:
an_array[6]

In [ ]:
start = 2
end = 18
step = 2

an_array[start:end:step]

In [ ]:
# Son equivalentes
#an_array[0:end:]
#an_array[:end:]
an_array[:end]

In [ ]:
an_array[:-1]

In [ ]:
an_array[::]

In [ ]:
an_array[::-1]

In [ ]:
for element in an_array[:5]:
    print(element)

In [ ]:
a_matrix = np.arange(16).reshape((4,4))
a_matrix

In [ ]:
a_matrix[:,2]

In [ ]:
a_matrix[:,1:3]

In [ ]:
a_matrix[-1,:]

In [ ]:
for row in a_matrix:
    print(row)

**EJERCICIO**: Multiplicar la submatriz principal superior e inferior de A de orden 3

In [ ]:
...

## Tipos de asignación

### Referencia

In [129]:
another_array = np.arange(10)
another_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [132]:
an_array = another_array

In [134]:
an_array[3] = 8
another_array

array([0, 1, 2, 8, 4, 5, 6, 7, 8, 9])

### Vista

In [135]:
another_array = np.arange(10)
another_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
an_array = another_array.view()

In [138]:
an_array = an_array.reshape((5,2))
an_array

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [139]:
another_array[3] = 8

In [140]:
an_array

array([[0, 1],
       [2, 8],
       [4, 5],
       [6, 7],
       [8, 9]])

### Copia

In [142]:
another_array = np.arange(10)

In [143]:
an_array = another_array.copy()

In [144]:
an_array[3] = 8

In [146]:
an_array, another_array

(array([0, 1, 2, 8, 4, 5, 6, 7, 8, 9]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))